version: 2.1
commands:
  install-bazel-linux-rbe:
    steps:
      - run: curl -OL https://raw.githubusercontent.com/graknlabs/build-tools/master/ci/apt-wait.sh
      - run: bash ./apt-wait.sh && rm ./apt-wait.sh
      - run: curl -OL https://raw.githubusercontent.com/graknlabs/build-tools/master/ci/install-bazel-linux.sh
      - run: bash ./install-bazel-linux.sh && rm ./install-bazel-linux.sh
      - run: curl -OL https://raw.githubusercontent.com/graknlabs/build-tools/master/ci/install-bazel-rbe.sh
      - run: bash ./install-bazel-rbe.sh && rm ./install-bazel-rbe.sh

jobs:
  test:
    machine: true
    working_directory: ~/kglib
    steps:
      - run: echo "Hello"
#      - install-bazel-linux-rbe
#      - checkout
#      - run: pyenv install 3.6.3
#      - run: pyenv global 3.6.3
#      - run: bazel test //kglib/... --test_output=streamed --spawn_strategy=standalone --python_version PY3 --python_path $(which python)

  deploy-pip-snapshot:
    machine: true
    working_directory: ~/kglib
    steps:
      - run: echo "Hello"
#      - install-bazel-linux-rbe
#      - checkout
#      - run: pyenv install 3.6.3
#      - run: pyenv global 3.6.3
#      - run: |
#          echo -n "$(cat VERSION)-$CIRCLE_SHA1" > VERSION
#          export DEPLOY_PIP_USERNAME=$REPO_GRAKN_USERNAME
#          export DEPLOY_PIP_PASSWORD=$REPO_GRAKN_PASSWORD
#          bazel run //:deploy-pip -- snapshot

  test-deployment-pip:
      machine: true
      working_directory: ~/kglib
      steps:
        - run: echo "Hello"
#        - checkout
#        - run: pyenv install 3.6.3
#        - run: pyenv global 3.6.3
#        - run: wget https://storage.googleapis.com/kglib/grakn-core-all-mac-animaltrade1.5.3.zip
#        - run: unzip grakn-core-all-mac-animaltrade1.5.3.zip
#        - run: nohup grakn-core-all-mac-animaltrade1.5.3/grakn server start
#        - run:
#            name: Run test-deployment-pip for kglib
#            command: |
#              echo -n "$(cat VERSION)-$CIRCLE_SHA1" > VERSION
#              sed -i -e "s/KGLIB_VERSION_MARKER/$(cat VERSION)/g" test/deployment/requirements.txt
#              cat test/deployment/requirements.txt
#              pip install -r test/deployment/requirements.txt
#              python -m unittest examples.kgcn.animal_trade.test.end_to_end_test

  release-approval:
    machine: true
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run: pyenv install 3.6.3
      - run: pyenv global 3.6.3
      - run: |
          export RELEASE_APPROVAL_USERNAME=$REPO_GITHUB_USERNAME
          export RELEASE_APPROVAL_TOKEN=$REPO_GITHUB_TOKEN
          bazel run @graknlabs_build_tools//ci:release-approval

  deploy-git:
    machine: true
    working_directory: ~/kglib
    steps:
      - checkout
      - run: wget https://github.com/tcnksm/ghr/releases/download/v0.12.0/ghr_v0.12.0_linux_386.tar.gz
      - run: tar xvf ghr_v0.12.0_linux_386.tar.gz
      - run: |
          pip install certifi
          export RELEASE_NOTES_TOKEN=$REPO_GITHUB_TOKEN
          bazel run @graknlabs_build_tools//ci:release-notes -- grakn $(cat VERSION) ./RELEASE_TEMPLATE.md
      - run:
         name: "Publish Draft Release on GitHub"
         command: |
           VERSION_TAG="v"$(cat "VERSION")
           curl -X POST --fail --data "{\"tag_name\": \"${VERSION_TAG}\",\"target_commitish\": \"${CIRCLE_SHA1}\",\"name\": \"Draft\",\"body\": \"\",\"draft\": true,\"prerelease\": false}" https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases?access_token=${GITHUB_DEPLOYMENT_TOKEN}

  deploy-pip-release:
    machine: true
    working_directory: ~/kglib
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run: pyenv install 3.6.3
      - run: pyenv global 3.6.3
#      - run: |
#          export DEPLOY_PIP_USERNAME=$REPO_PYPI_USERNAME
#          export DEPLOY_PIP_PASSWORD=$REPO_PYPI_PASSWORD
#          bazel run //:deploy-pip -- release

  release-cleanup:
    machine: true
    steps:
      - checkout
      - run: git push --delete origin kglib-release-branch

workflows:
  kglib:
    jobs:
      - test
      - deploy-pip-snapshot:
          requires:
            - test
      - test-deployment-pip:
          requires:
            - deploy-pip-snapshot
      - release-approval:
          requires:
            - test-deployment-pip
  kglib-release:
    jobs:
      - deploy-git:
          filters:
            branches:
              only: kglib-release-branch
      - deploy-approval:
          type: approval
          filters:
            branches:
              only: kglib-release-branch
          requires:
            - deploy-git
      - deploy-pip-release:
          filters:
            branches:
              only: kglib-release-branch
          requires:
            - deploy-approval
      - release-cleanup:
          filters:
            branches:
              only: kglib-release-branch
          requires:
            - deploy-pip-release
